### ISSUE TITLE
Will you be my mentor?

### ISSUE THREAD

**Issue by pavanjadhaw** [sarthology/ResolutionBoard#1]
Dear Sarthak,

My name is Pavan Jadhaw and I am currently pursuing under-graduation in computer science I have enjoyed many of your post on dev.to and learned from your open source projects.

I was going through your repository when I found this one and I was glad to know that you are looking to mentor youngsters.

I am at the point where I feel I need some mentoring to more effectively develop skills so that I can prepare and become better developer.

So I would like to ask, "Will you be my mentor?"

Thank you for your time and I look forward to it.

Best Regards.

Pavan Jadhaw

**Comment by sarthology** [comment]
Yes, I will my friend.

**Comment by pavanjadhaw** [comment]
So where do I start, I am so excited for this :tada:

**Comment by sarthology** [comment]
DM me on twitter @sarthology

**Comment by pavanjadhaw** [comment]
Hey sorry but I couldnt dm you on twitter because of your privacy settings.
My twitter handle @pavanjadhaw
