### ISSUE TITLE
New logo

### ISSUE THREAD

**Issue by benedekrozemberczki** [sarthology/ResolutionBoard#2]
Are you going to create a new logo?

**Comment by sarthology** [comment]
Do you have any ideas ?

**Comment by benedekrozemberczki** [comment]
Would be happy to use the same logo with a different year.

**Comment by sarthology** [comment]
Ohk Give me a day, it will be updated.

**Comment by benedekrozemberczki** [comment]
How is it going?

**Comment by sarthology** [comment]
It's done boss.
